### ISSUE TITLE
any plan to wrap the payment API ?

### ISSUE THREAD

**Issue by fix** [cubyn/gocardless#1]

**Comment by getvega** [comment]
Hello @fix -- this is certainly something we will add next week or so.
Contributions welcome otherwise ;-)

**Comment by vroudge** [comment]
@fix We'd be glad to check any PR :)

**Comment by fix** [comment]
ok i'll work on it starting next year, on my task list

**Comment by getvega** [comment]
PR https://github.com/cubyn/gocardless/pull/2
